### ISSUE TITLE
Convert to Shiny App

### ISSUE THREAD

**Issue by gringer** [carsweshau/POREquality#2]
Given that this is already an R Markdown document, it should be possible to convert this to a Shiny App with a button click for uploading [gzipped?] sequencing summary files.

*[consider this a placeholder to remind me to submit a pull request; other people are free to have a go at implementing this themselves]*

**Comment by carsweshau** [comment]
Thanks for the suggestion - I've been a bit snowed under and just catching up on this, so apologies for the delay! That sounds like functionality I'd appreciate, so will certainly look into it.
